#!/bin/bash

echo "[0/4] Installing development limix version"

rm /tmp/limix.XXXX.log >/dev/null 2>&1 || true

logfile=$(mktemp /tmp/limix.XXXX.log)
exec 3>"$logfile"

function silent_run
{
    eval "$@ >&3 2>&1"
}

function silent_trun
{
    eval "$@ >&3 2>&1 || true"
}

function do_then_sudo
{
    eval "$@"
    if [ $? != 0 ]; then
        eval "sudo $@"
    fi
}

function failed
{
    echo "FAILED."
    echo "[_/_] LOG OUTPUT:"
    cat $logfile
    exit 1
}

GIT_URL=https://github.com/limix/limix.git
GIT_FOLDER=$(pwd)/limix-dev

echo -n "[1/5] Cloning repository... "
silent_run git clone -b develop $GIT_URL $GIT_FOLDER
cd $GIT_FOLDER
[ $? == 0 ] && echo "done." || failed

function install_deps
{
    bash <(curl -fsSL https://raw.githubusercontent.com/limix/hcephes/master/install)
    bash <(curl -fsSL https://raw.githubusercontent.com/limix/liknorm/master/install)
}

echo -n "[2/4] Installing C dependencies... "
silent_run install_deps
[ $? == 0 ] && echo "done." || failed

echo -n "[3/4] Installing Python dependencies... "
silent_run pip install -r requirements.txt
[ $? == 0 ] && echo "done." || failed

echo -n "[4/4] Installing limix itself... "
silent_run python setup.py develop
[ $? == 0 ] && echo "done." || failed

rm "$logfile" || true
